LOAD DATA 
INFILE 'ConceptDimension.csv'
BADFILE 'ConceptDimension.bad'
DISCARDFILE 'ConceptDimension.dsc'
APPEND 
INTO TABLE i2b2demodata.Concept_Dimension
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY "`"
TRAILING NULLCOLS
( 
CONCEPT_CD,
CONCEPT_PATH char(4000),
NAME_CHAR,
CONCEPT_BLOB char(1),
UPDATE_DATE "NVL(:UPDATE_DATE,sysdate)",
DOWNLOAD_DATE "NVL(:DOWNLOAD_DATE,sysdate)",
IMPORT_DATE "NVL(:IMPORT_DATE,sysdate)",
SOURCESYSTEM_CD,
UPLOAD_ID,
X FILLER
)