LOAD DATA 
INFILE 'ObjectMapping.csv'
BADFILE 'ObjectMapping.bad'
DISCARDFILE 'ObjectMapping.dsc'
TRUNCATE 
INTO TABLE i2b2demodata.Object_Mapping
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY "`"
TRAILING NULLCOLS
( 
SOURCE_ID,
TABLE_REF,
COLUMN_REF,
SOURCE_NAME,
MAPPED_ID
)