drop index I2B2DEMODATA.CONCEPT_COUNTS_INDEX1;
drop index I2B2DEMODATA.CONCEPT_DIMENSION_PK;
drop index I2B2DEMODATA.CD_UPLOADID_IDX;
drop index I2B2DEMODATA.PATIENT_DIMENSION_PK;
drop index I2B2DEMODATA.PD_IDX_DATES;
drop index I2B2DEMODATA.PD_IDX_ALLPATIENTDIM;
drop index I2B2DEMODATA.PD_IDX_STATECITYZIP;
drop index I2B2DEMODATA.PATD_UPLOADID_IDX;
drop index I2B2DEMODATA.PM_UPLOADID_IDX;
drop index I2B2DEMODATA.PM_PATNUM_IDX;
drop index I2B2DEMODATA.PM_ENCPNUM_IDX;

  ALTER TABLE I2B2DEMODATA.CONCEPT_COUNTS NOLOGGING;
  ALTER TABLE I2B2DEMODATA.CONCEPT_DIMENSION NOLOGGING;
  ALTER TABLE I2B2DEMODATA.OBSERVATION_FACT NOLOGGING;
  ALTER TABLE I2B2METADATA.I2B2 NOLOGGING;

  commit;

  exit;