  DROP INDEX "I2B2METADATA"."I2B2_CF_IDX";

  DROP INDEX "I2B2METADATA"."I2B2_CF_CH_CV_CSC";

  DROP INDEX "I2B2METADATA"."I2B2_CF_MAP_MCD_IDX";

  DROP INDEX "I2B2METADATA"."I2B2_INDEX5";

  DROP INDEX "I2B2DEMODATA"."IDX_CC_PCP_PC";

  DROP INDEX "I2B2DEMODATA"."IDX_CC_PCP_PC_CP";

  DROP INDEX "I2B2DEMODATA"."IDX_CONCEPT_DIM3";

  DROP INDEX "I2B2DEMODATA"."IDX_CONCEPT_DIM_1";
