
'\'||DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)||'\'
--------------------------------------------------------------------------------
\
  CREATE INDEX "I2B2DEMODATA"."OM_SI_SN_MI_IDX" ON "I2B2DEMODATA"."OBJECT_MAPP

\
  CREATE INDEX "I2B2DEMODATA"."IDX_CC_PCP_PC" ON "I2B2DEMODATA"."CONCEPT_COUNT

\
  CREATE INDEX "I2B2DEMODATA"."IDX_CC_PCP_PC_CP" ON "I2B2DEMODATA"."CONCEPT_CO

\
  CREATE INDEX "I2B2DEMODATA"."IDX_CONCEPT_DIM3" ON "I2B2DEMODATA"."CONCEPT_DI

'\'||DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME,OWNER)||'\'
--------------------------------------------------------------------------------

\
  CREATE INDEX "I2B2DEMODATA"."IDX_CONCEPT_DIM_1" ON "I2B2DEMODATA"."CONCEPT_D

\
  CREATE INDEX "I2B2DEMODATA"."PATIENT_DIMENSION_INDEX1" ON "I2B2DEMODATA"."PA

\
  CREATE INDEX "I2B2DEMODATA"."PD_IDX_ALLPATIENTDIM" ON "I2B2DEMODATA"."PATIEN


7 rows selected.

