/
DECLARE
  TYPE T_TABLE IS TABLE OF VARCHAR2(4000);
  
  P_OWNER VARCHAR2(4000) := '';
  P_TABLE_NAME VARCHAR2(4000) := '';
  
  V_CMD VARCHAR2(4000);
  V_TABLE_ARRAY T_TABLE;
  
BEGIN
  
  SELECT DISTINCT 'ANALYZE TABLE ' || OWNER || '.' || TABLE_NAME  || ' COMPUTE STATISTICS' BULK COLLECT INTO V_TABLE_ARRAY FROM DBA_INDEXES WHERE OWNER = 'I2B2METADATA' AND TABLE_NAME = 'I2B2' AND INDEX_TYPE = 'NORMAL';
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
    
  SELECT DISTINCT 'ANALYZE TABLE ' || OWNER || '.' || TABLE_NAME  || ' COMPUTE STATISTICS' BULK COLLECT INTO V_TABLE_ARRAY FROM DBA_INDEXES WHERE OWNER = 'I2B2DEMODATA' AND TABLE_NAME = 'CONCEPT_DIMENSION' AND INDEX_TYPE = 'NORMAL';
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
    
  SELECT DISTINCT 'ANALYZE TABLE ' || OWNER || '.' || TABLE_NAME  || ' COMPUTE STATISTICS' BULK COLLECT INTO V_TABLE_ARRAY FROM DBA_INDEXES WHERE OWNER = 'I2B2DEMODATA' AND TABLE_NAME = 'OBSERVATION_FACT' AND INDEX_TYPE = 'NORMAL';
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
  
  SELECT 'drop MATERIALIZED VIEW ' || owner || '.' || MVIEW_NAME BULK COLLECT INTO V_TABLE_ARRAY FROM dba_mviews WHERE owner = 'I2B2DEMODATA' AND MVIEW_NAME = 'OBS_FACT_CON_PAT_MVW';  
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
  
  SELECT 'CREATE MATERIALIZED VIEW "I2B2DEMODATA"."OBS_FACT_CON_PAT_MVW" ("CONCEPT_CD", "CONCEPT_PATH","PATIENT_NUM")
          partition by hash ( CONCEPT_PATH )
          partitions 8192 
          NOCOMPRESS NOLOGGING NO INMEMORY
          TABLESPACE "TRANSMART" 
          BUILD IMMEDIATE
          USING INDEX
          REFRESH COMPLETE ON DEMAND
          USING DEFAULT LOCAL ROLLBACK SEGMENT
          USING ENFORCED CONSTRAINTS ENABLE QUERY REWRITE
          AS SELECT /*+ USE_HASH(OBS,CD)*/ distinct OBS.CONCEPT_CD,
              CD.CONCEPT_PATH,
              OBS.PATIENT_NUM
                  FROM
                  "I2B2DEMODATA".OBSERVATION_FACT OBS,
                  "I2B2DEMODATA".CONCEPT_DIMENSION CD
                  WHERE CD.CONCEPT_CD = OBS.CONCEPT_CD
            AND (OBS.MODIFIER_CD = ''@'' OR OBS.MODIFIER_CD IS NULL)' BULK COLLECT INTO V_TABLE_ARRAY FROM DUAL;
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
            
  SELECT 'CREATE INDEX "I2B2METADATA"."IDX_OF_CPM_PN" ON "I2B2DEMODATA"."OBS_FACT_CON_PAT_MVW" ("PATIENT_NUM")
  NOLOGGING TABLESPACE "TRANSMART" COMPUTE STATISTICS' BULK COLLECT INTO V_TABLE_ARRAY FROM DUAL;
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
  
  SELECT 'CREATE INDEX "I2B2METADATA"."IDX_OF_CPM_CP_PN" ON "I2B2DEMODATA"."OBS_FACT_CON_PAT_MVW" ("CONCEPT_PATH","PATIENT_NUM")
  NOLOGGING TABLESPACE "TRANSMART" COMPUTE STATISTICS LOCAL' BULK COLLECT INTO V_TABLE_ARRAY FROM DUAL;
  FOR V_INDEX IN 1 .. V_TABLE_ARRAY.COUNT LOOP
    V_CMD := V_TABLE_ARRAY(V_INDEX);
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
  
END;

/
exit;