LOAD DATA 
INFILE 'ModifierDimension.csv'
BADFILE 'ModifierDimension.bad'
DISCARDFILE 'ModifierDimension.dsc'
TRUNCATE 
INTO TABLE i2b2demodata.Modifier_Dimension
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY "`"
TRAILING NULLCOLS
( 
MODIFIER_PATH char(4000),
MODIFIER_CD,
NAME_CHAR char(4000),
MODIFIER_BLOB char(10),
UPDATE_DATE "NVL(:UPDATE_DATE,sysdate)",
DOWNLOAD_DATE "NVL(:DOWNLOAD_DATE,sysdate)",
IMPORT_DATE "NVL(:IMPORT_DATE,sysdate)",
SOURCESYSTEM_CD,
UPLOAD_ID
)